import ChemSimTools as cst

startFlux = cst.Flux('StartFlux', 23)
startFlux.add_compound({'name': 'H20', '%': 70})
startFlux.add_compound({'name': 'NaCl', '%': 30})
flux1 = cst.Flux('Flux1', None)
flux1.add_compound({'name': 'H20', '%': 70})
flux1.add_compound({'name': 'NaCl', '%': 30})
flux2 = cst.Flux('Flux2', 10)
flux2.add_compound({'name': 'H20', '%': 70})
flux2.add_compound({'name': 'NaCl', '%': 30})
machine1 = cst.Machine('Machine1')
machine1.add_flux_in(startFlux)
machine1.add_flux_out(flux1)
machine1.add_flux_out(flux2)
system1 = cst.System('System1')
system1.add_machine(machine1)
print(system1.solve())
print(flux1.speed)
